name: Publish packages to NPM

on:
  release:
    types: [created]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      id-token: write
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish package to NPM
        env:
          IS_PRERELEASE: ${{ github.event.release.prerelease }}
        run: |
          TAG=${GITHUB_REF:10}
          echo "Processing tag: $TAG"
          MODULE=`echo "$TAG" | sed -e 's/@ibm-verify\/\([a-zA-Z].*\)@.*$/\1/'`
          # This step would fail if module is not a valid sdk 
          cd ${GITHUB_WORKSPACE}/sdk/${MODULE}
          if [ "$IS_PRERELEASE" = "true" ]; then
            echo "It's a pre-release."
            npm publish --dry-run --access public
          else
            echo "It's a release."
            npm publish --access public
          fi
