name: Publish packages to NPM

on:
  release:
    types: [created]
  push:
    tags:
      - '**'

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      id-token: write
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - name: Publish package to NPM
        env:
          EVENT_TYPE: ${{ github.event_name }}
          IS_PRERELEASE: ${{ github.event.release.prerelease }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Update npm"
          npm install -g npm@latest

          TAG=${GITHUB_REF:10}
          echo "Processing tag: $TAG"
          MODULE=`echo "$TAG" | sed -e 's/@ibm-verify\/\([a-zA-Z].*\)@.*$/\1/'`
          # This step would fail if module is not a valid sdk 
          cd ${GITHUB_WORKSPACE}/sdk/${MODULE}
        
          # echo "Building package"
          # npm ci
          # npm run build --if-present

          if [[ "$EVENT_TYPE" == "push" || ["$IS_PRERELEASE" == "true" ]]; then
            echo "It's a pre-release."
            npm publish --dry-run --access public
          else
            echo "It's a release."
            npm publish --access public
          fi
