name: Push documentation to github pages repo

env:
  GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}

# Trigger the workflow on push to main or when a github release is created
on:
  push:
    branches:
      - main
    tags:
    - '**'
  release:
    types: [created]

jobs:
  pushdocs:
    name: Push SDK documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sdk monorepo
        uses: actions/checkout@v2
        with:
          path: monorepo

      - name: Checkout github docs repo
        uses: actions/checkout@v2
        with:
          repository: ibm-verify/ibm-verify.github.io
          path: docs

      - name: Install npm
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Authorize GitHub CLI
        env:
          GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_API_TOKEN }}
        run: |
          env -u GH_PAGES_TOKEN gh auth login --with-token <<< "$GH_PAGES_TOKEN"
      
      - name: Push docs
        env:
          GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_API_TOKEN }}
        run: ${{ github.workspace }}/monorepo/.github/scripts/pushdocs.sh
        shell: bash
